### ISSUE TITLE
The 0.1.12 release does not contain built msgs

### ISSUE THREAD

**Issue by Chrismacolor** [faust-computer/geist_common#11]
@entire Latest common ts package 0.1.12 does not contain the built msgs types.  I am assuming the build command didn't run?

**Comment by entire** [comment]
@Chrismacolor - what is the best way to check if this is the case? 

Also - let me try to release it again. Will release a v0.1.13

**Comment by entire** [comment]
I republished v0.1.13 

cc: @Chrismacolor
